<script lang="ts">
	import '../app.css';
	import { invalidate } from '$app/navigation';
	import { page } from '$app/state';
	import { ModeWatcher } from 'mode-watcher';
	import { Toaster } from '$lib/components/ui/sonner';
	import AppNav from '$lib/components/AppNav.svelte';
	import ReloadPrompt from '$lib/components/ReloadPrompt.svelte';
	import { pwaInfo } from 'virtual:pwa-info';

	let { data, children } = $props();

	const supabase = $derived(data.supabase);
	const showChrome = $derived(page.url.pathname !== '/login');
	const webManifest = $derived(pwaInfo?.webManifest?.linkTag ?? '');

	// Keep server-side load functions in sync when the auth state changes in this tab.
	$effect(() => {
		const {
			data: { subscription }
		} = supabase.auth.onAuthStateChange((_, newSession) => {
			if (newSession?.expires_at !== data.session?.expires_at) invalidate('supabase:auth');
		});
		return () => subscription.unsubscribe();
	});
</script>

<svelte:head>
	<link rel="icon" href="/favicon.png" />
	<link rel="apple-touch-icon" href="/icon-192.png" />
	<meta name="theme-color" content="#0c0a09" />
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by the PWA plugin -->
	{@html webManifest}
</svelte:head>

<ModeWatcher />
<Toaster position="top-center" richColors />
<ReloadPrompt />

{#if showChrome}
	<div class="bg-background min-h-svh md:flex">
		<AppNav />
		<main class="min-w-0 flex-1 pb-24 md:pb-0">
			{@render children()}
		</main>
	</div>
{:else}
	{@render children()}
{/if}
