<script lang="ts">
	import '../app.css';
	import { ModeWatcher } from 'mode-watcher';
	import { Toaster } from '$lib/components/ui/sonner';
	import AppNav from '$lib/components/AppNav.svelte';
	import ReloadPrompt from '$lib/components/ReloadPrompt.svelte';
	import { pwaInfo } from 'virtual:pwa-info';
	import { base } from '$app/paths';

	let { children } = $props();

	const webManifest = $derived(pwaInfo?.webManifest?.linkTag ?? '');
</script>

<svelte:head>
	<link rel="icon" href="{base}/favicon.png" />
	<link rel="apple-touch-icon" href="{base}/icon-192.png" />
	<meta name="theme-color" content="#0c0a09" />
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated by the PWA plugin -->
	{@html webManifest}
</svelte:head>

<ModeWatcher />
<Toaster position="top-center" richColors />
<ReloadPrompt />

<div class="bg-background min-h-svh md:flex">
	<AppNav />
	<main class="min-w-0 flex-1 pb-24 md:pb-0">
		{@render children()}
	</main>
</div>
